// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCR5En-dbdOK6xfQdLBvzwymIT2JN134Ig',
    appId: '1:742432606035:web:73a6c4faafe43ffd66c3a6',
    messagingSenderId: '742432606035',
    projectId: 'jihc-clubs',
    authDomain: 'jihc-clubs.firebaseapp.com',
    storageBucket: 'jihc-clubs.firebasestorage.app',
    measurementId: 'G-5VMSW4R2X2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCn6sdujQlGCGiUNNks4oSu2a4QbStkwIA',
    appId: '1:742432606035:android:913e4138b1af8e3f66c3a6',
    messagingSenderId: '742432606035',
    projectId: 'jihc-clubs',
    storageBucket: 'jihc-clubs.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAa2GauTf0Gt-VBgnvVYIHZ3AxkO8S7dcg',
    appId: '1:742432606035:ios:1ca8cf76b65e75e966c3a6',
    messagingSenderId: '742432606035',
    projectId: 'jihc-clubs',
    storageBucket: 'jihc-clubs.firebasestorage.app',
    iosClientId:
        '742432606035-uq1djtb5u0me6eitf29sc09ekn0on9lq.apps.googleusercontent.com',
    iosBundleId: 'com.example.jihcClubsHub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAa2GauTf0Gt-VBgnvVYIHZ3AxkO8S7dcg',
    appId: '1:742432606035:ios:1ca8cf76b65e75e966c3a6',
    messagingSenderId: '742432606035',
    projectId: 'jihc-clubs',
    storageBucket: 'jihc-clubs.firebasestorage.app',
    iosClientId:
        '742432606035-uq1djtb5u0me6eitf29sc09ekn0on9lq.apps.googleusercontent.com',
    iosBundleId: 'com.example.jihcClubsHub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCR5En-dbdOK6xfQdLBvzwymIT2JN134Ig',
    appId: '1:742432606035:web:63832c1345432d9266c3a6',
    messagingSenderId: '742432606035',
    projectId: 'jihc-clubs',
    authDomain: 'jihc-clubs.firebaseapp.com',
    storageBucket: 'jihc-clubs.firebasestorage.app',
    measurementId: 'G-2T8BYGF5RD',
  );
}
